### ISSUE TITLE
I am getting no such file or directory

### ISSUE THREAD

**Issue by jd-solanki** [juliangruber/read-file-action#15]
My workflow file content:
```yml
    steps:
      - name: Read package.json
        id: readme
        uses: juliangruber/read-file-action@v1.1.4
        with:
          path: ./README.md
      - name: Echo readme
        run: echo "${{ steps.readme.outputs.content }}"
```

My repo content

![Screenshot 2022-01-25 at 1 15 53 PM](https://user-images.githubusercontent.com/47495003/150933472-2f5c1c7d-741f-4959-a99e-b7a3edab87d5.png)

Also, If I create the action of my own just like yours. I am also getting the same error.

Do you know why? 🤔
